## Day Agenda
- Data science Life cycle
- Data science Libraries

## Data science life cycle
- involves 6 stpes
    - business undertsanding
    - data prep
    - data munging/data Wrangling
        - feature selection (eg:- clothes, furniture etc)
        - EDA Tool (Exploratory Data Analysis)
    - model training
    - model evaluation
    - model deployment
        - aws
        - IBM waston studio
    - model tracking

## Data Analysis Libraries
- Numpy (mostly used fo mathematical operations on integers) (numerical python)
- Pandas (also used fo creating data frames)
- Matplotlib (mostly used for data visualization)
- Seaborn
- Scipy

In [1]:
import numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

## Creatiing arrays

In [2]:
import numpy as np
# inbluilt as arrays in numpy
x=np.array(23)
print(x)
np.ndim(x)  # check dimension

23


0

In [4]:
x1=np.array([12,23,4,5,6])
print(x1)
np.ndim(x1) #1-D array

[12 23  4  5  6]


1

In [9]:
# 2-D array
x2=np.array([[1,2,3]])
print(x2)
np.ndim(x2)

[[1 2 3]]


2

In [5]:
# 2D
x3=np.array([[1,2,3],[1,3,4]])
print(x3)
print(np.ndim(x3))
print(np.size(x3))
print("to get rows and cols:" , np.shape(x3))

[[1 2 3]
 [1 3 4]]
2
6
to get rows and cols: (2, 3)


In [16]:
## 3D array
## - [[[]]]
x4=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x4)
print("dimension of x4: ",np.ndim(x4))
print("elements of x4 ",np.size(x4))
print("shape of x4",np.shape(x4)) 
# 3-rows and 3-cols 
## inside a 1 dim array we have 2 dimension array so that is why we get 1 in shape

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension of x4:  3
elements of x4  9
shape of x4 (1, 3, 3)


## Methods to create arrays
- Zeros
- Ones
- linspacce
- logspace
- arrange

In [20]:
a0 = np.zeros(2)
print(a0)
a1=np.zeros(3)
print(a1)

[0. 0.]
[0. 0. 0.]


In [22]:
a2=np.zeros(4,dtype=int)
a2

array([0, 0, 0, 0])

In [23]:
a2=np.zeros(4,dtype=str)
a2

array(['', '', '', ''], dtype='<U1')

In [24]:
a3=np.ones(5,dtype=int)
a3

array([1, 1, 1, 1, 1])

In [15]:
a4=np.zeros(5,dtype=int)
a5=a4.reshape(1,5)
print("a4 :",a4)
print("a5 :",a5)
a6=a4.reshape(5,1)
print("a6 :",a6)

a4 : [0 0 0 0 0]
a5 : [[0 0 0 0 0]]
a6 : [[0]
 [0]
 [0]
 [0]
 [0]]


In [16]:
a=np.arange(1,12,2) # elem from 1 to 12 with dif 2
print(a)
print(" dim :",np.ndim(a))
print("Elements :",np.size(a))

[ 1  3  5  7  9 11]
 dim : 1
Elements : 6


In [38]:
# possibilities to reshape of 6 elements
#- (2,3)
#- (3,2)
#- (6,1)
#- (1,6)
a1=a.reshape(2,3)
print(a)
print(a1)

[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]


In [42]:
l1=np.logspace(1,5,3)
print(l1)

[1.e+01 1.e+03 1.e+05]


In [47]:
l2=np.linspace(1,5,6)
l2

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [49]:
r=np.random.rand(3,2)
r

array([[0.04390663, 0.87373151],
       [0.59756826, 0.49925386],
       [0.90907492, 0.36736142]])

In [50]:
r=np.random.rand(3,2)
r

array([[0.460749  , 0.52575853],
       [0.81686304, 0.38945297],
       [0.47480029, 0.59552192]])

In [54]:
r1=np.random.randint(1,10)
r1

3

In [19]:
r1=np.random.randn(1,10)
r1

array([[-0.20442672, -0.13664179, -0.19012233,  0.18148381,  0.12665418,
        -1.88709483, -0.0750473 ,  0.25801895, -0.76478339, -0.37444796]])

In [60]:
np.ndim(r1)

2

In [20]:
r3=r1.flatten() #to convert matrix to 1D
r3

array([-0.20442672, -0.13664179, -0.19012233,  0.18148381,  0.12665418,
       -1.88709483, -0.0750473 ,  0.25801895, -0.76478339, -0.37444796])

In [63]:
np.ndim(r3)

1

## Accessing elements in arrays
1. indexing
    - +ve
    - -ve
2. slicing [start:stop:step]
3. loop
    - for
    - while