## Day agenda
- indexing
- filtering
- statistics
- aggregation
- saving data

In [6]:
import numpy as np
x1=np.array([1,2,3,5,6,7])
x2=np.array([[1,2,3],[4,5,6]])
print(x1)
print(x2)

[1 2 3 5 6 7]
[[1 2 3]
 [4 5 6]]


In [7]:
print(x1[0])
print(x1[2])

1
3


In [8]:
print(x2[0::2])
print(x1[0::2])
print(x1[0:4])

[[1 2 3]]
[1 3 6]
[1 2 3 5]


In [13]:
print(x1[0::1])

[1 2 3]


In [15]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x2[0]

array([1, 2, 3])

In [9]:
print(x2[:,0]) #all rows oth col
print(x2[:,1]) #all rows 1st col
print(x2[:,2])

[1 4]
[2 5]
[3 6]


In [10]:
x2[0][2] #0th row 2nd col

3

In [11]:
x2[:,0:2]  #all rows and col-0 to 2 i.e., 0 and 2-1=1

array([[1, 2],
       [4, 5]])

In [12]:
x2[:,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x2[:,0::2] # all rows with col dif of 2

array([[1, 3],
       [4, 6]])