## statistics

In [1]:
import numpy as np

In [3]:
x1=np.array([1,2,3])
x1

array([1, 2, 3])

In [4]:
np.min(x1)

1

In [5]:
np.max(x1)

3

In [6]:
np.median(x1)

2.0

In [7]:
np.percentile(x1,25)

1.5

In [8]:
np.percentile(x1,100)

3.0

In [10]:
np.percentile(x1,50)

2.0

In [11]:
np.sum(x1)

6

### Aggregation functions

In [12]:
x1

array([1, 2, 3])

In [13]:
x2=np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x2.sum()

21

In [15]:
x2.min()

1

In [16]:
x2.argmax() # index position of max values

5

In [18]:
x2.argmin() #index position of min value

0

In [19]:
x2.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [22]:
x2.cumprod() ## cumulative sum and product

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [24]:
x2.argmin(axis=1) # min element indx pos by col wise

array([0, 0], dtype=int64)

In [25]:
x2.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [27]:
x3=np.array([[1,4,5],[2,3,1]])
x3

array([[1, 4, 5],
       [2, 3, 1]])

In [31]:
x3.argmin(axis=1) #row wise

array([0, 2], dtype=int64)

In [32]:
x3.argmin(axis=0)

array([0, 1, 1], dtype=int64)

## saving data

In [33]:
x=np.random.rand(1,10)
x

array([[0.35904637, 0.29697123, 0.90121208, 0.25221526, 0.44478165,
        0.08324599, 0.57417381, 0.37269592, 0.02725038, 0.98363987]])

In [34]:
np.save("x.npy",x)

In [35]:
np.load("x.npy")

array([[0.35904637, 0.29697123, 0.90121208, 0.25221526, 0.44478165,
        0.08324599, 0.57417381, 0.37269592, 0.02725038, 0.98363987]])

## Numpy copy and view
- copy
    - changes will not get effected to the original array and vice versa
- view
    - changes will affected to the original array if change copied array
    - vice versa
    

In [40]:
## shallow copy as changes are not afftected 
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
print(" copied array:",x)
print("main array :",arr)
arr[0]=40
print(" copied array:",x)
print("main array :",arr)
x[0]=5
print(" copied array:",x)
print("main array :",arr)

 copied array: [1 2 3 4]
main array : [1 2 3 4]
 copied array: [1 2 3 4]
main array : [40  2  3  4]
 copied array: [5 2 3 4]
main array : [40  2  3  4]


In [42]:
import numpy as np
n1=np.array([55,66,44,22])
n2=n1.view() #deep copy
print(" copied array:",n2)
print("main array :",n1)
n1[0]=78
print(" copied array:",n2)
print("main array :",n1)

 copied array: [55 66 44 22]
main array : [55 66 44 22]
 copied array: [78 66 44 22]
main array : [78 66 44 22]


## numpy joining arrays
- np.concatenate()

In [44]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([8,7,6])
a3=np.concatenate((a1,a2))
a3

array([1, 2, 3, 8, 7, 6])

In [45]:
import numpy as np
b1=np.array([[1,2,3],[7,6,5]])
b2=np.array([[0,9,8],[6,4,5]])
b3=np.concatenate((b1,b2))
b3

array([[1, 2, 3],
       [7, 6, 5],
       [0, 9, 8],
       [6, 4, 5]])

In [46]:
np.hstack((b1,b2))

array([[1, 2, 3, 0, 9, 8],
       [7, 6, 5, 6, 4, 5]])

In [47]:
np.vstack((b1,b2))

array([[1, 2, 3],
       [7, 6, 5],
       [0, 9, 8],
       [6, 4, 5]])

In [48]:
b1

array([[1, 2, 3],
       [7, 6, 5]])

In [49]:
b2

array([[0, 9, 8],
       [6, 4, 5]])

## Numpy math functions
- sin
- cos
- tan

In [51]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [52]:
x.diagonal()

array([1, 4])

In [53]:
x.transpose()

array([[1, 3],
       [2, 4]])

In [55]:
x.sort()
x

array([[1, 2],
       [3, 4]])

In [59]:
a1=np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [61]:
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [62]:
np.tan(a1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [ ]:
## series ob